spring.application.name=cadent-consultorio

# Conexão com o PostgreSQL 15 local
spring.datasource.url=jdbc:postgresql://localhost:5433/cadente_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Exibição e formatação das queries SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true